### ISSUE TITLE
lmh gen regression

### ISSUE THREAD

**Issue by kohlhase** [KWARC/localmh#193]
I do a ``` lmh pdf -f``` in ```MathHub/smglom/smglom/source``` (using the dev branch) and get the error message
```
ALLTEX: Less jobs then available workers, using fewer workers. 
ALLTEX: 3 file(s) to generate using 3 workers. 
ALLTEX[9]: Generating /Users/kohlhase/localmh/MathHub/smglom/smglom/source/all.de.tex
ALLTEX[10]: Generating /Users/kohlhase/localmh/MathHub/smglom/smglom/source/all.en.tex
ALLTEX[11]: Generating /Users/kohlhase/localmh/MathHub/smglom/smglom/source/all.tex
ALLTEX[11]: Generated /Users/kohlhase/localmh/MathHub/smglom/smglom/source/all.tex
ALLTEX[10]: Generated /Users/kohlhase/localmh/MathHub/smglom/smglom/source/all.en.tex
ALLTEX[9]: Generated /Users/kohlhase/localmh/MathHub/smglom/smglom/source/all.de.tex
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/lmh-1.7.4-py2.7.egg/lmh_core/__init__.py", line 289, in main
    run_lmh(install)
  File "/Library/Python/2.7/site-packages/lmh-1.7.4-py2.7.egg/lmh_core/__init__.py", line 88, in run_lmh
    s.main()
  File "/Users/kohlhase/localmh/bin/lmh", line 11, in main
    lmh.run(sys.argv[1:])
  File "/Users/kohlhase/localmh/bin/../lmh/__init__.py", line 128, in run
    if main(argv):
  File "/Users/kohlhase/localmh/bin/../lmh/__init__.py", line 111, in main
    return submods["gen"].do(parser.parse_args(argv))
  File "/Users/kohlhase/localmh/bin/../lmh/commands/gen.py", line 156, in do
    (res, d, f) = lmh.lib.modules.generators.run(modules, args.verbose, args.update, args.quiet, args.workers, lmh.lib.modules.generators.alltex, args.grep_log)
  File "/Users/kohlhase/localmh/bin/../lmh/lib/modules/generators/__init__.py", line 92, in run
    write_log_files(the_generator, d, f)
  File "/Users/kohlhase/localmh/bin/../lmh/lib/modules/generators/__init__.py", line 239, in write_log_files
    if d["path"] in logs:
KeyError: 'path'

lmh seems to have crashed with <type 'exceptions.KeyError'>
a report will be generated in 
```
Note also that the last line of the error message seems to be incomplete

**Comment by tkw1536** [comment]
@kohlhase I have implemented a really quick and dirty fix, can you please test?

**Comment by kohlhase** [comment]
seems to work for me.

**Comment by tkw1536** [comment]
@kohlhase Good, closing.
