### ISSUE TITLE
lmh mvmod regression

### ISSUE THREAD

**Issue by kohlhase** [KWARC/localmh#206]
I get 
```
smglom kohlhase$ lmh mvmod smglom/smglom smglom/identities cassiniidentity catalanidentity lebesgueidentity ramanujanidentity
updating paths in the following files: 
Traceback (most recent call last):
  File "/usr/local/bin/lmh", line 14, in <module>
    main()
  File "/usr/local/bin/lmh", line 11, in main
    lmh.run(sys.argv[1:])
  File "/path/to/localmh/bin/../lmh/__init__.py", line 128, in run
    if main(argv):
  File "/path/to/localmh/bin/../lmh/__init__.py", line 122, in main
    return submods[args.action].do(args)
  File "/path/to/localmh/bin/../lmh/commands/mvmod.py", line 49, in do
    return movemod(args.source, args.dest, args.module, args.no_depcrawl, simulate=args.simulate)
  File "/path/to/localmh/bin/../lmh/lib/modules/move.py", line 157, in movemod
    res1 = find_cached(files, finds, replace=replaces)
  File "/path/to/localmh/bin/../lmh/lib/repos/find_and_replace.py", line 120, in find_cached
    rep = find_and_replace_file(file, matcher, replace, replace_match = replace_match) or rep
  File "/path/to/localmh/bin/../lmh/lib/repos/find_and_replace.py", line 61, in find_and_replace_file
    file_content = read_file(file)
  File "/path/to/localmh/bin/../lmh/lib/io.py", line 200, in read_file
    text_file = open(filename, "r")
IOError: [Errno 2] No such file or directory: '/path/to/localmh/MathHub/MiKoMH/talks/source/jacobs/talks/.#seng.tex'

lmh seems to have crashed with <type 'exceptions.IOError'>
a report will be generated in 
```
when I redo this, then it seems to work, so it is more annoying than hindering.

**Comment by tkw1536** [comment]
Can not reproduce. I can only guess that a weirdly named file is somewhere in your cloned repositories and the python library can not split filename and thing directly.

**Comment by kohlhase** [comment]
then let's ignore this.
