### ISSUE TITLE
lmh gen --sms failure 

### ISSUE THREAD

**Issue by angerhang** [KWARC/localmh#236]
@tkw1536 I have reinstalled `lmh` but still run into an error:

This is a detailed look
```log
<ncalvin/localmh/MathHub/angerhang/GenCS/source/SMl/en# lmh gen --sms                   
Resolving for content to be generated, this might take a bit ...
Traceback (most recent call last):
  File "/usr/local/bin/lmh", line 13, in <module>
    main()
  File "/usr/local/bin/lmh", line 10, in main
    lmh.run(sys.argv[1:])
  File "/path/to/localmh/bin/../lmh/__init__.py", line 85, in run
    if main(argv):
  File "/path/to/localmh/bin/../lmh/__init__.py", line 79, in main
    return submods[args.action].do(args, unknown)
  File "/path/to/localmh/bin/../lmh/commands/gen/__init__.py", line 27, in do
    return run.do(arguments, unparsed)
  File "/path/to/localmh/bin/../lmh/commands/gen/run.py", line 24, in do
    return run_paralell(args.pathspec, args.workers, targets, args.silent)
  File "/path/to/localmh/bin/../lmh/lib/modules/compile/runner.py", line 66, in run_paralell
    groups = get_build_groups(spec)
  File "/path/to/localmh/bin/../lmh/lib/modules/__init__.py", line 147, in get_build_groups
    paths = locate_compile_targets(spec)
  File "/path/to/localmh/bin/../lmh/lib/modules/__init__.py", line 139, in locate_compile_targets
    modules = reduce([locate_compile_target(p) for p in paths])
  File "/path/to/localmh/bin/../lmh/lib/modules/__init__.py", line 109, in locate_compile_target
    repo_name = os.path.relpath(repo_dir, data_dir)
  File "/usr/lib/python2.7/posixpath.py", line 435, in relpath
    raise ValueError("no path specified")
ValueError: no path specified

lmh seems to have crashed with <type 'exceptions.ValueError'>
a report will be generated in 
<ncalvin/localmh/MathHub/angerhang/GenCS/source/SMl/en# git branch                      
  dev
* master
```

**Comment by angerhang** [comment]
`Git clone` was causing the issue and  `lmh install` did the trick.
