### ISSUE TITLE
lmh gbranch --init fails

### ISSUE THREAD

**Issue by cmaeder** [KWARC/localmh#251]
```
maeder@lati:/var/data/localmh/MathHub/MMT/LATIN$ lmh gbranch --init twelf-omdoc
Creating branch 'twelf-omdoc' at 'twelf-omdoc'. 
Traceback (most recent call last):
  File "/path/to/localmh/bin/lmh", line 13, in <module>
    main()
  File "/path/to/localmh/bin/lmh", line 10, in main
    lmh.run(sys.argv[1:])
  File "/path/to/localmh/bin/../lmh/__init__.py", line 85, in run
    if main(argv):
  File "/path/to/localmh/bin/../lmh/__init__.py", line 79, in main
    return submods[args.action].do(args, unknown)
  File "/path/to/localmh/bin/../lmh/commands/gbranch/__init__.py", line 27, in do
    return run.do(arguments, unparsed)
  File "/path/to/localmh/bin/../lmh/commands/gbranch/run.py", line 23, in do
    return gen.init_branch(args.branch)
  File "/path/to/localmh/bin/../lmh/lib/repos/gbranch.py", line 182, in init_branch
    if not make_orphan_branch(rpath, name):
  File "/path/to/localmh/bin/../lmh/lib/git.py", line 155, in make_orphan_branch
    treeid = proc.communicate(input=b'')[0].rstrip("\n")
TypeError: Type str doesn't support the buffer API

lmh seems to have crashed with <class 'TypeError'>
a report will be generated in 
```

**Comment by tkw1536** [comment]
Fixed. Was caused by the recent migration to python3.

**Comment by cmaeder** [comment]
A decent language would detect type errors at compile time! Is there no python-lint are something similar. Waiting for all type errors to occur at user's runtime is not nice.

**Comment by tkw1536** [comment]
Python is interpreted, so compile time = run time.

**Comment by cmaeder** [comment]
yes, not decent!

**Comment by cmaeder** [comment]
see #252 Did you revert something?

**Comment by cmaeder** [comment]
probably reintroduced by @kohlhase  merge
