### ISSUE TITLE
lmh gbranch --init does not create a branch (and push it) as advertised

### ISSUE THREAD

**Issue by cmaeder** [KWARC/localmh#252]
only the entry in `META-INF/MANIFEST.MF` is created. A subsequent `--install` fails.

```
maeder@lati:/var/data/localmh/MathHub/MMT/LATIN$ lmh gbranch --init twelf-omdoc
Creating branch 'twelf-omdoc' at 'twelf-omdoc'. 
maeder@lati:/var/data/localmh/MathHub/MMT/LATIN$ lmh gbranch --install twelf-omdoc
error: the requested upstream branch 'origin/twelf-omdoc' does not exist
hint: 
hint: If you are planning on basing your work on an upstream
hint: branch that already exists at the remote, you may need to
hint: run "git fetch" to retrieve it.
hint: 
hint: If you are planning to push out a new local branch that
hint: will track its remote counterpart, you may want to use
hint: "git push -u" to set the upstream config as you push.
```

**Comment by tkw1536** [comment]
Looks like this to me: 
![1444395738964](https://cloud.githubusercontent.com/assets/2923242/10394329/bc3368fc-6e96-11e5-9250-81b736e86cd9.png)

```
lmh gbranch --init
```

should automatically install the new branch.

**Comment by cmaeder** [comment]
it does not work for me! It finishes immediately with `Creating branch 'test2' at 'test2'.`

**Comment by tkw1536** [comment]
I can try to reproduce the bug on my other machine later, otherwise it will have to wait until monday.

**Comment by cmaeder** [comment]
Monday will be fine

**Comment by cmaeder** [comment]
Currently it fails with:

```
maeder@lati:/var/data/localmh/MathHub/MMT/LATIN$ lmh gbranch --init twelf-omdocCreating branch 'twelf-omdoc' at 'twelf-omdoc'. 
Traceback (most recent call last):
  File "/path/to/localmh/bin/lmh", line 13, in <module>
    main()
  File "/path/to/localmh/bin/lmh", line 10, in main
    lmh.run(sys.argv[1:])
  File "/path/to/localmh/bin/../lmh/__init__.py", line 85, in run
    if main(argv):
  File "/path/to/localmh/bin/../lmh/__init__.py", line 79, in main
    return submods[args.action].do(args, unknown)
  File "/path/to/localmh/bin/../lmh/commands/gbranch/__init__.py", line 27, in do
    return run.do(arguments, unparsed)
  File "/path/to/localmh/bin/../lmh/commands/gbranch/run.py", line 23, in do
    return gen.init_branch(args.branch)
  File "/path/to/localmh/bin/../lmh/lib/repos/gbranch.py", line 182, in init_branch
    if not make_orphan_branch(rpath, name):
  File "/path/to/localmh/bin/../lmh/lib/git.py", line 155, in make_orphan_branch
    treeid = proc.communicate(input=b'')[0].rstrip("\n")
TypeError: Type str doesn't support the buffer API

lmh seems to have crashed with <class 'TypeError'>
a report will be generated in 
```

**Comment by cmaeder** [comment]
git user.name and user.email was not set in docker
