### ISSUE TITLE
lmh setup --update crashes

### ISSUE THREAD

**Issue by kohlhase** [KWARC/localmh#295]
with 
```
Successfully installed LaTeXML-v0.8.1
1 distribution installed
Already up-to-date.
Traceback (most recent call last):
  File "/path/to/localmh/bin/lmh", line 13, in <module>
    main()
  File "/path/to/localmh/bin/lmh", line 10, in main
    lmh.run(sys.argv[1:])
  File "/mounted/lmh/lmh/__init__.py", line 85, in run
    if main(argv):
  File "/mounted/lmh/lmh/__init__.py", line 79, in main
    return submods[args.action].do(args, unknown)
  File "/mounted/lmh/lmh/commands/setup/__init__.py", line 27, in do
    return run.do(arguments, unparsed)
  File "/mounted/lmh/lmh/commands/setup/run.py", line 24, in do
    return lmh.lib.packs.update(*args.pack)
  File "/mounted/lmh/lmh/lib/packs/__init__.py", line 137, in update
    ret = update_pack(pack) or ret
  File "/mounted/lmh/lmh/lib/packs/__init__.py", line 124, in update_pack
    return pack_setup.update(pack_dir, pconfig)
  File "/mounted/lmh/lmh/lib/packs/classes.py", line 39, in update
    if not self.do_update(pack_dir, params):
  File "/mounted/lmh/lmh/lib/packs/setups/self.py", line 10, in do_update
    return pull(lmh_locate)
  File "/mounted/lmh/lmh/lib/git.py", line 52, in pull
    return do(dest, "pull", *arg)
  File "/mounted/lmh/lmh/lib/git.py", line 14, in do
    proc = subprocess.Popen(args, stderr=sys.stderr, stdout=sys.stdout, cwd=dest)
  File "/usr/lib/python3.4/subprocess.py", line 859, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.4/subprocess.py", line 1395, in _execute_child
    restore_signals, start_new_session, preexec_fn)
TypeError: Can't convert 'function' object to str implicitly

lmh seems to have crashed with <class 'TypeError'>
a report will be generated in 
Michaels-MacBook-Pro:Downloads kohlhase$ 
``` 
on my mac

**Comment by tkw1536** [comment]
Looks like an internal python bug. I will check if I can reproduce it later.

**Comment by angerhang** [comment]
Yeah I am also having the same problem.
