### ISSUE TITLE
chleanup branch: lmh setup --update broken

### ISSUE THREAD

**Issue by kohlhase** [KWARC/localmh#306]
I get 
```
Michaels-MBP:localmh kohlhase$ lmh setup --update
Traceback (most recent call last):
  File "/path/to/localmh/bin/lmh", line 13, in <module>
    import shell
  File "/mounted/lmh/shell.py", line 9, in <module>
    from lmh.frontend import main
  File "/mounted/lmh/lmh/__init__.py", line 2, in <module>
    from lmh.systems.manager import SystemManager
  File "/mounted/lmh/lmh/systems/__init__.py", line 2, in <module>
    from lmh.systems.manager import SystemManager
  File "/mounted/lmh/lmh/systems/manager.py", line 1, in <module>
    from typing import Optional, List
```

**Comment by kohlhase** [comment]
Actually, I get the same on all commands, switching back to master.

**Comment by tkw1536** [comment]
That traceback is unusually helpless (no actual error message, just a traceback. ) I was not able to reproduce this (as of yesterday everything worked fine). But I will try again.
