### ISSUE TITLE
lmh gen on master does not work 

### ISSUE THREAD

**Issue by kohlhase** [KWARC/localmh#308]
I get the error 
```
 lmh pdf sets-introduction.tex 
Traceback (most recent call last):
  File "/path/to/localmh/bin/lmh", line 13, in <module>
    main()
  File "/path/to/localmh/bin/lmh", line 10, in main
    lmh.run(sys.argv[1:])
  File "/path/to/localmh/lmh/__init__.py", line 85, in run
    if main(argv):
  File "/path/to/localmh/lmh/__init__.py", line 79, in main
    return submods[args.action].do(args, unknown)
  File "/path/to/localmh/lmh/commands/mmt/__init__.py", line 27, in do
    return run.do(arguments, unparsed)
  File "/path/to/localmh/lmh/commands/mmt/run.py", line 5, in do
    return run(unknown)
  File "/path/to/localmh/lmh/lib/mmt.py", line 21, in run
    proc = subprocess.Popen([mmt_executable] + args, stderr=subprocess.PIPE if quiet else sys.stderr, stdout=subprocess.PIPE if quiet else sys.stdout, cwd=path)
  File "/usr/lib/python3.4/subprocess.py", line 859, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.4/subprocess.py", line 1457, in _execute_child
    raise child_exception_type(errno_num, err_msg)
OSError: [Errno 8] Exec format error

lmh seems to have crashed with <class 'OSError'>
a report will be generated in 
Michaels-MBP-2:en kohlhase$ 

```

**Comment by tkw1536** [comment]
This is probably related to running jars directly or as java -jar FILENAME. I will have a more detailed look later today.

**Comment by tkw1536** [comment]
@kohlhase I have pushed a possible fix, but I do not have my mac with me to test (works on linux). Can you test and let me know if it works?

**Comment by kohlhase** [comment]
I ran ```lmh setup --update``` and also ```git pull``` and here is the result
```
lmh pdf sets-introduction.tex 
/path/to/localmh/ext/MMT/deploy/mmt.jar
Error: Invalid or corrupt jarfile /path/to/localmh/ext/MMT/deploy/mmt.jar
```
so something changed, but not enough.

**Comment by tkw1536** [comment]
Simple explanation: The binary release URI for mmt was changed and lmh wasn't updated. Pointed it back to a working URI, @Jazzpirate is pushing a new jar later today. After an update and ```lmh setup --reinstall MMT``` everything should be back to normal.

**Comment by kohlhase** [comment]
I have tried that and get 
```
Michaels-MBP-2:en kohlhase$ lmh setup --reinstall MMT
Pack MMT could not be (re)installed, --reset has failed. 
```

**Comment by angerhang** [comment]
I ran into the same error 
```shell
Hangs-MacBook-Pro:~ Hang$ lmh setup --reinstall MMT
Pack MMT could not be (re)installed, --reset has failed. 
```
so this is not just specific to miko's setup.

**Comment by tkw1536** [comment]
It seems to work on Michaels machine now, so closing this issue.
